{{- if .Values.account.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskndo.fullname" . }}-account
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.account.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.account.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "taskndo.fullname" . }}-account
{{- end }}
