{{- if .Values.miiverseApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: miiverse-api
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.miiverseApi.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.miiverseApi.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: miiverse-api
{{- end }}
