{{- if .Values.miiverseWeb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miiverse-web
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
    app: miiverse-web
spec:
  replicas: {{ .Values.miiverseWeb.replicaCount }}
  selector:
    matchLabels:
      app: miiverse-web
  template:
    metadata:
      labels:
        app: miiverse-web
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          imagePullPolicy: Always
          command: ['sh', '-c', 'until nc -z -w 2 mongo {{ .Values.mongo.service.port }}; do echo waiting for mongo; sleep 2; done']
      containers:
        - name: miiverse-web
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.miiverseWeb.image.repository }}:{{ .Values.miiverseWeb.image.tag }}"
          imagePullPolicy: {{ .Values.miiverseWeb.image.pullPolicy }}
          env:
            - name: PN_JUXTAPOSITION_UI_HTTP_PORT
              value: {{ .Values.miiverseWeb.service.httpPort | quote }}
            - name: PN_JUXTAPOSITION_UI_REDIS_HOST
              value: {{ if .Values.redis.enabled }}"redis"{{ else }}{{ .Values.miiverseWeb.env.redisHost | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_REDIS_PORT
              value: {{ if .Values.redis.enabled }}{{ .Values.redis.service.port | quote }}{{ else }}{{ .Values.miiverseWeb.env.redisPort | quote }}{{ end }}
            
            - name: PN_JUXTAPOSITION_UI_MONGOOSE_URI
              value: {{ if .Values.mongo.enabled }}"mongodb://mongo:{{ .Values.mongo.service.port }}/miiverse?directConnection=true"{{ else }}{{ .Values.miiverseApi.env.mongooseUri | quote }}{{ end }}

            - name: PN_JUXTAPOSITION_UI_S3_ENDPOINT
              value: {{ if .Values.minio.enabled }}"http://minio:{{ .Values.minio.service.port }}"{{ else }}{{ .Values.miiverseApi.env.s3Endpoint | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_S3_KEY
              value: {{ if .Values.minio.enabled }}{{ .Values.minio.env.rootUser | quote }}{{ else }}{{ .Values.miiverseApi.env.s3Key | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_S3_SECRET
              value: {{ if .Values.minio.enabled }}{{ .Values.minio.env.rootPassword | quote }}{{ else }}{{ .Values.miiverseApi.env.s3Secret | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_S3_BUCKET
              value: {{ if .Values.minio.enabled }}{{ .Values.minio.env.bucket | quote }}{{ else }}{{ .Values.miiverseApi.env.s3Bucket | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_S3_REGION
              value: {{ .Values.miiverseApi.env.s3Region | quote }}

            - name: PN_JUXTAPOSITION_UI_GRPC_FRIENDS_HOST
              value: friends
            - name: PN_JUXTAPOSITION_UI_GRPC_FRIENDS_PORT
              value: {{ .Values.friends.service.grpcPort | quote }}
            - name: PN_JUXTAPOSITION_UI_GRPC_FRIENDS_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}

            - name: PN_JUXTAPOSITION_UI_GRPC_ACCOUNT_HOST
              value: account
            - name: PN_JUXTAPOSITION_UI_GRPC_ACCOUNT_PORT
              value: {{ .Values.account.service.grpcPort | quote }}
            - name: PN_JUXTAPOSITION_UI_GRPC_ACCOUNT_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_JUXTAPOSITION_UI_GRPC_MIIVERSE_HOST
              value: miiverse-api
            - name: PN_JUXTAPOSITION_UI_GRPC_MIIVERSE_PORT
              value: {{ .Values.miiverseApi.service.grpcPort | quote }}
            - name: PN_JUXTAPOSITION_UI_GRPC_MIIVERSE_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_JUXTAPOSITION_UI_AES_KEY
              value: {{ .Values.global.aesKey | quote }}
            - name: PN_JUXTAPOSITION_UI_CDN_DOMAIN
              value: {{ if .Values.minio.enabled }}"http://minio:{{ .Values.minio.service.port }}/{{ .Values.minio.env.bucket }}"{{ else }}{{ .Values.miiverseWeb.env.cdnDomain | quote }}{{ end }}
            - name: PN_JUXTAPOSITION_UI_WHITELIST
              value: {{ .Values.miiverseWeb.env.whitelist | quote }}
            - name: PN_JUXTAPOSITION_UI_SERVER_ENVIRONMENT
              value: {{ .Values.global.serverEnvironment | quote }}
            - name: PN_JUXTAPOSITION_UI_DISABLE_CONSOLE_CHECKS
              value: {{ .Values.miiverseWeb.env.disableConsoleChecks | quote }}
            - name: PN_JUXTAPOSITION_UI_HTTP_BASE_URL
              value: {{ .Values.miiverseWeb.env.httpBaseUrl | quote }}
            - name: PN_JUXTAPOSITION_UI_DOMAINS_WEB
              value: {{ .Values.miiverseWeb.env.domainsWeb | quote }}
            - name: PN_JUXTAPOSITION_UI_DOMAINS_CTR
              value: {{ .Values.miiverseWeb.env.domainsCtr | quote }}
            - name: PN_JUXTAPOSITION_UI_DOMAINS_PORTAL
              value: {{ .Values.miiverseWeb.env.domainsPortal | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.miiverseWeb.service.httpPort }}
              protocol: TCP
{{- end }}
