{{- if .Values.miiverseWeb.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: miiverse-web
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.global.gateway.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.miiverseWeb.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: miiverse-web
          port: {{ .Values.miiverseWeb.service.httpPort }}
{{- end }}
