{{- if .Values.mongo.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
    app: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
          env:
            - name: GLIBC_TUNABLES
              value: glibc.pthread.rseq=1
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 27017
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    app: mongo
{{- end }}
