{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskndo.fullname" . }}-nginx-config
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        underscores_in_headers on;
        
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers 'DEFAULT:@SECLEVEL=0';
        ssl_prefer_server_ciphers on;
        proxy_ssl_verify off;
        proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        
        log_format requests '$remote_addr - [$time_local] '
                            '"$request" '
                            'method="$request_method" '
                            'host="$host" '
                            'uri="$uri" '
                            'args="$args" '
                            'status=$status';
        access_log  /var/log/nginx/access.log  requests;
        sendfile        on;
        keepalive_timeout  65;
        include /etc/nginx/conf.d/*.conf;
    }

  default.conf: |
    # Map for account domains
    server {
        listen 80;
        listen 443 ssl;
        server_name {{ join " " .Values.account.hostnames }};
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location / {
            proxy_pass http://{{ include "taskndo.fullname" . }}-account:{{ .Values.account.service.httpPort }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    # Map for miiverse domains
    server {
        listen 80;
        listen 443 ssl;
        server_name {{ join " " .Values.miiverseApi.hostnames }};
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location / {
            proxy_pass http://{{ include "taskndo.fullname" . }}-miiverse-api:{{ .Values.miiverseApi.service.httpPort }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    # Map for juxt domains
    server {
        listen 80;
        listen 443 ssl;
        server_name {{ join " " .Values.miiverseWeb.hostnames }};
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location / {
            proxy_pass http://{{ include "taskndo.fullname" . }}-miiverse-web:{{ .Values.miiverseWeb.service.httpPort }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
    
    # Map for S3 domains (MinIO)
    server {
        listen 80;
        listen 443 ssl;
        server_name cdn.n.tasklab.dev r2-cdn.n.tasklab.dev;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location / {
            proxy_pass http://minio:{{ .Values.minio.service.port }};
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
{{- end }}
