{{- if .Values.triForceHeroes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tri-force-heroes
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
    app: tri-force-heroes
spec:
  replicas: {{ .Values.triForceHeroes.replicaCount }}
  selector:
    matchLabels:
      app: tri-force-heroes
  template:
    metadata:
      labels:
        app: tri-force-heroes
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          imagePullPolicy: Always
          command: ['sh', '-c', 'until nc -z -w 2 mongo {{ .Values.mongo.service.port }}; do echo waiting for mongo; sleep 2; done']
        - name: wait-for-postgres
          image: busybox:1.36
          imagePullPolicy: Always
          command: ['sh', '-c', 'until nc -z -w 2 postgres {{ .Values.postgres.service.port }}; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: tri-force-heroes
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.triForceHeroes.image.repository }}:{{ .Values.triForceHeroes.image.tag }}"
          imagePullPolicy: {{ .Values.triForceHeroes.image.pullPolicy }}
          env:
            - name: PN_TFH_POSTGRES_URI
              value: {{ .Values.triForceHeroes.env.postgresUri | quote }}
            - name: PN_TFH_AUTHENTICATION_SERVER_PORT
              value: {{ .Values.triForceHeroes.service.authPort | quote }}
            - name: PN_TFH_SECURE_SERVER_HOST
              value: {{ .Values.triForceHeroes.env.secureServerHost | default .Values.global.primaryServerIp | quote }}
            - name: PN_TFH_SECURE_SERVER_PORT
              value: {{ .Values.triForceHeroes.service.securePort | quote }}
            - name: PN_TFH_ACCOUNT_GRPC_HOST
              value: account
            - name: PN_TFH_ACCOUNT_GRPC_PORT
              value: {{ .Values.account.service.grpcPort | quote }}
            - name: PN_TFH_ACCOUNT_GRPC_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_TFH_FRIENDS_GRPC_HOST
              value: friends
            - name: PN_TFH_FRIENDS_GRPC_PORT
              value: {{ .Values.friends.service.grpcPort | quote }}
            - name: PN_TFH_FRIENDS_GRPC_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_TFH_AES_KEY
              value: {{ .Values.global.aesKey | quote }}
          ports:
            - name: auth-tcp
              containerPort: {{ .Values.triForceHeroes.service.authPort }}
              protocol: TCP
            - name: auth-udp
              containerPort: {{ .Values.triForceHeroes.service.authPort }}
              protocol: UDP
            - name: secure-tcp
              containerPort: {{ .Values.triForceHeroes.service.securePort }}
              protocol: TCP
            - name: secure-udp
              containerPort: {{ .Values.triForceHeroes.service.securePort }}
              protocol: UDP
{{- end }}
