{{- if .Values.triForceHeroes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskndo.fullname" . }}-tri-force-heroes
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
    app: {{ include "taskndo.fullname" . }}-tri-force-heroes
spec:
  replicas: {{ .Values.triForceHeroes.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "taskndo.fullname" . }}-tri-force-heroes
  template:
    metadata:
      labels:
        app: {{ include "taskndo.fullname" . }}-tri-force-heroes
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: tri-force-heroes
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.triForceHeroes.image.repository }}:{{ .Values.triForceHeroes.image.tag }}"
          imagePullPolicy: {{ .Values.triForceHeroes.image.pullPolicy }}
          env:
            - name: PN_TFH_POSTGRES_URI
              value: {{ .Values.triForceHeroes.env.postgresUri | quote }}
            - name: PN_TFH_AUTHENTICATION_SERVER_PORT
              value: {{ .Values.triForceHeroes.service.authPort | quote }}
            - name: PN_TFH_SECURE_SERVER_HOST
              value: {{ .Values.triForceHeroes.env.secureServerHost | default .Values.global.primaryServerIp | quote }}
            - name: PN_TFH_SECURE_SERVER_PORT
              value: {{ .Values.triForceHeroes.service.securePort | quote }}
            - name: PN_TFH_ACCOUNT_GRPC_HOST
              value: {{ include "taskndo.fullname" . }}-account
            - name: PN_TFH_ACCOUNT_GRPC_PORT
              value: {{ .Values.account.service.grpcPort | quote }}
            - name: PN_TFH_ACCOUNT_GRPC_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_TFH_FRIENDS_GRPC_HOST
              value: {{ include "taskndo.fullname" . }}-friends
            - name: PN_TFH_FRIENDS_GRPC_PORT
              value: {{ .Values.friends.service.grpcPort | quote }}
            - name: PN_TFH_FRIENDS_GRPC_API_KEY
              value: {{ .Values.global.masterApiKey | quote }}
            - name: PN_TFH_AES_KEY
              value: {{ .Values.global.aesKey | quote }}
          ports:
            - name: auth-tcp
              containerPort: {{ .Values.triForceHeroes.service.authPort }}
              protocol: TCP
            - name: auth-udp
              containerPort: {{ .Values.triForceHeroes.service.authPort }}
              protocol: UDP
            - name: secure-tcp
              containerPort: {{ .Values.triForceHeroes.service.securePort }}
              protocol: TCP
            - name: secure-udp
              containerPort: {{ .Values.triForceHeroes.service.securePort }}
              protocol: UDP
{{- end }}
