{{- if .Values.triForceHeroes.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: tri-force-heroes
  labels:
    {{- include "taskndo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.triForceHeroes.service.type | default "NodePort" }}
  ports:
    - port: {{ .Values.triForceHeroes.service.authPort }}
      targetPort: auth-tcp
      protocol: TCP
      name: auth-tcp
      nodePort: {{ .Values.triForceHeroes.service.authPort }}
    - port: {{ .Values.triForceHeroes.service.authPort }}
      targetPort: auth-udp
      protocol: UDP
      name: auth-udp
      nodePort: {{ .Values.triForceHeroes.service.authPort }}
    - port: {{ .Values.triForceHeroes.service.securePort }}
      targetPort: secure-tcp
      protocol: TCP
      name: secure-tcp
      nodePort: {{ .Values.triForceHeroes.service.securePort }}
    - port: {{ .Values.triForceHeroes.service.securePort }}
      targetPort: secure-udp
      protocol: UDP
      name: secure-udp
      nodePort: {{ .Values.triForceHeroes.service.securePort }}
  selector:
    app: tri-force-heroes
{{- end }}
